# Sales Data Analysis
## Data Loading

In [2]:
import pandas as pd
df = pd.read_csv("sales_dataset.csv")

## Data Validation

In [3]:
df.head()

,CustomerId,OrderDate,SalesOrderNumber,Subtotal,TaxAmt,Freight,TotalDue,ProductID,ProductName,OrderQty,LineTotal
0,29847,2008-06-01 00:00:00.000,SO71774,"880,3484","70,4279","22,0087","972,785",836,"ML Road Frame-W - Yellow, 48",1,356.898
1,29847,2008-06-01 00:00:00.000,SO71774,"880,3484","70,4279","22,0087","972,785",822,"ML Road Frame-W - Yellow, 38",1,356.898
2,30072,2008-06-01 00:00:00.000,SO71776,"78,81","6,3048","1,9703","87,0851",907,Rear Brakes,1,63.900
3,30113,2008-06-01 00:00:00.000,SO71780,"38418,6895","3073,4952","960,4672","42452,6519",905,"ML Mountain Frame-W - Silver, 42",4,873.816
4,30113,2008-06-01 00:00:00.000,SO71780,"38418,6895","3073,4952","960,4672","42452,6519",983,"Mountain-400-W Silver, 46",2,923.388

In [4]:
df.dtypes

CustomerId            int64
OrderDate               str
SalesOrderNumber        str
Subtotal                str
TaxAmt                  str
Freight                 str
TotalDue                str
ProductID             int64
ProductName             str
OrderQty              int64
LineTotal           float64
dtype: object

In [5]:
df.isnull().sum()

CustomerId          0
OrderDate           0
SalesOrderNumber    0
Subtotal            0
TaxAmt              0
Freight             0
TotalDue            0
ProductID           0
ProductName         0
OrderQty            0
LineTotal           0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df.count()

CustomerId          542
OrderDate           542
SalesOrderNumber    542
Subtotal            542
TaxAmt              542
Freight             542
TotalDue            542
ProductID           542
ProductName         542
OrderQty            542
LineTotal           542
dtype: int64

In [8]:
df["CustomerId"].unique().size

32

In [9]:
df["ProductID"].unique().size

142

In [10]:
df["SalesOrderNumber"].unique().size

32

In [11]:
df["Subtotal"] = df["Subtotal"].str.replace(",", ".")
df["Subtotal"] = df["Subtotal"].astype(float)
print(df["Subtotal"])

0        880.3484
1        880.3484
2         78.8100
3      38418.6895
4      38418.6895
          ...
537    88812.8625
538    88812.8625
539    88812.8625
540    88812.8625
541       38.9536
Name: Subtotal, Length: 542, dtype: float64

In [12]:
df.dtypes

CustomerId            int64
OrderDate               str
SalesOrderNumber        str
Subtotal            float64
TaxAmt                  str
Freight                 str
TotalDue                str
ProductID             int64
ProductName             str
OrderQty              int64
LineTotal           float64
dtype: object

## 3 Basic Business Metrics

In [13]:
total_rev = df["Subtotal"].sum()
print(f"Total revenue: {round((total_rev),2)}")

total_orders = int(df["SalesOrderNumber"].unique().size)
print(f"Total orders: {total_orders}")

total_customers = int(df["CustomerId"].unique().size)
print(f"Total customers: {total_customers}")

avg_order = total_rev / total_orders 
print(f"Average order value: {round((avg_order),2)}")

Total revenue: 32447380.9
Total orders: 32
Total customers: 32
Average order value: 1013980.65

In [47]:
grouped = df.groupby("CustomerId")
result = grouped["LineTotal"].sum()
result_df = pd.DataFrame(result)
result_df["NOO"] = grouped["SalesOrderNumber"].nunique()
result_df["AOV"] = result_df["LineTotal"] / result_df["NOO"]
result_df["Products_purchased"] = grouped["ProductID"].count()
result_df["Revenue_share"] = result_df["LineTotal"] / total_rev * 100.0
result_df = result_df.sort_values("LineTotal", ascending=False)
result_df["Cumulative_revenue"] = result_df["LineTotal"].cumsum() / total_rev * 100.0

result_df.head(4)

,LineTotal,NOO,AOV,Products_purchased,Revenue_share,Cumulative_revenue
CustomerId,,,,,,
29736,89869.276314,1,89869.276314,43,0.276969,0.276969
30050,79589.616024,1,79589.616024,46,0.245288,0.522258
29546,74160.228000,1,74160.228000,42,0.228555,0.750813
29957,65683.367986,1,65683.367986,43,0.202430,0.953243

In [ ]:
grouped = df.groupby("CustomerId").agg({
    "LineTotal": "sum",
    "SalesOrderNumber": "nunique",
    "ProductID":"count"
}).rename(columns = {
    "LineTotal" : "Revenue",
    "SalesOrderNumber" : "UniqueOrders",
    "ProductID" : "ProductsPurchased"

}).reset_index().sort_values("Revenue", ascending = False)

grouped["Revenue_share"] = grouped["Revenue"] / total_rev * 100.0
grouped["Cumulative_revenue"] = grouped["Revenue"].cumsum() / total_rev * 100.0

grouped.head(4)